version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - mysql_database:/var/lib/mysql

  nginx:
    build: data/nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/workdir
      - ./data/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  minio:
    image: minio/minio
    ports:
      - "9001:9000"
    volumes:
      - miniodb:/export
    environment:
      MINIO_ACCESS_KEY: FN1E9STQYQ9LE077SNWC
      MINIO_SECRET_KEY: ThgAalM0ljoXhRHenaXdjxHHvT596706gS0Reuiv
    command: server /export

  redis:
    image: redis:alpine

  php:
    build: data/php
    depends_on:
      - db
      - minio
      - redis

    volumes:
      - ./www:/workdir
      - ./data/php/php_custom.ini:/usr/local/etc/php/conf.d/php_custom.ini
volumes:
  mysql_database:
  miniodb:
